ncubook/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Log In Page
    path('login/', authViews.LoginView.as_view(
        template_name='ncubook/login.html'), name='login'),
    
    # Home Page
    path('', views.index, name='index'), 
    
    # Search
    path('search/', views.search, name='search'),

    # Search By Coarse Branch
    path('search/<str:coarse_branch>/', views.search_by_coarse_branch, name='search_by_coarse_branch'),

    # Privacy Policy  Page 
    path('privacy/', views.privacy, name='privacy'),

    # Terms & Conditions  Page
    path('terms/', views.terms, name='terms'),

    # About us Page
    path('about/', views.about, name='about'),

    # Contact us Page
    path('contact/', views.contact, name='contact'),
        
    # Log Out Page
    path('logout/', views.logout, name='logout'),    
]

posts/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Add Post
    path('add_post/', views.add_post, name='add_post'), 

    # Like Post
    path('like_post/<int:post_id>/', views.like_post),

    # Report Post
    path('report_post/<int:post_id>/', views.report_post),

    # Delete Post
    path('delete_post/<int:post_id>/', views.delete_post),

    # Post Comments Page
    path('post_comments/<int:post_id>/', views.post_comments, name='post_comments'), 

    # Report Comment
    path('report_comment/<int:comment_id>/', views.report_comment),

    # Add Comment
    path('add_comment/', views.add_comment), 

    # Delete Comment
    path('delete_comment/<int:comment_id>/', views.delete_comment),    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        # Khan Diary url config.
        path('', include(('ncubook.urls', 'ncubook'), namespace='ncubook')),

        # Users url config.
        path('', include(('users.urls', 'users'), namespace='users')),

        # Posts url config.
        path('', include(('posts.urls', 'posts'), namespace='posts')),

        # Messenger url config.
        path('', include(('messenger.urls', 'messenger'), namespace='messenger')),

        # Notifications url config.
        path('', include(('notifications.urls', 'notifications'), namespace='notifications')),

        # Admin url config
        path('admin/', admin.site.urls), 

        # Detect Timezone
        path('tz_detect/', include('tz_detect.urls')),
]

# Admin portal config.
admin.site.site_header = 'NCUbook Adminstration'
admin.site.index_title = 'Site Administration'
admin.site.site_title = "NCUbook - Admin"

users/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    # Sign Up Page    
    path('signup/', views.signup, name='signup'),

    # Password Reset Confirm
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),

    # Password Reset 
    path('password_reset/<int:user_id>/', views.password_reset, name='password_reset'),

    # Profile Page
    path('<str:username>/profile', views.profile, name='profile'), 

    # Buddies Page
    path('<str:user>/buddies', views.buddies, name='buddies'),

    # Remove Buddy 
    path('remove_buddy/<int:user_id>/', views.remove_buddy),

    # Send Buddy Request
    path('send_request/<int:user_id>/', views.send_request),

    # Accept Buddy Request
    path('accept_request/<int:request_id>/', views.accept_request),

    # Reject Buddy Request
    path('reject_request/<int:request_id>/', views.reject_request),

    # Buddy Requests Page
    path('buddy_requests', views.buddy_requests, name='buddy_requests'), 

    # Edit Profile Page
    path('edit_profile/', views.edit_profile, name='edit_profile'), 

    # Verify Account Link
    path('verify_account_link/', views.verify_account_link, name='verify_account_link'),

    # Verify Account 
    path('verify_account/', views.verify_account, name='verify_account'),

    # Login Details Page
    path('login_details/', views.login_details, name='login_details'),

    # Settings / Change Password Page
    path('settings/change_password/', views.change_password, name='change_password'),     
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from .forms import SignUpForm, UserUpdateForm, ChangePasswordForm, PasswordResetForm, ProfileUpdateForm, AccountVerifyForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, Http404
from .models import Profile, BuddyRequest
from notifications.models import Notification
from posts.models import Post
from django.core.mail import send_mail
import random


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            # Split Name In First Name & Last Name
            name = name.split(" ")
            first_name = name[0]

            # Extract Last Name In String Form
            raw_last_name = name[1:]
            last_name = ""
            for ele in raw_last_name:
                last_name += ele + " "
           
            new_user = User.objects.create_user(
                first_name=first_name, last_name=last_name, username=username.lower(), password=password)

            # create_profile(new_user)
            Profile.objects.create(user=new_user)
            
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            messages.success(
                request, f'{first_name}, You are most welcome on NCUbook! please complete your profile.')
            return redirect('users:edit_profile')

        else:
            messages.error(
                request, f'Unable to create  account! Please correct the errors below.')            

    else:
        form = SignUpForm()

    context = {'form': form}

    return render(request, 'users/signup.html', context)

def password_reset_confirm(request):
    context = {} # For Get Request
    if request.method == "POST":
        username = request.POST.get("username")
        context['username'] = username
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            user_id = user.id

            # Generate & Save OTP
            raw_otp = random.randint(1000, 9999)
            user.profile.otp = raw_otp
            user.profile.save()

            # Send OTP Email
            recipient_list = [user.profile.email,]
            send_mail(
                "OTP for NCUbook password reset.",
                f"OTP: {str(raw_otp)} (Ignore if you did not requested this.)",
                "NCUBook",
                recipient_list,
                fail_silently=True,
            )              

            messages.success(
                request, f'OTP has been sent on your NCU email adress.')
            return redirect('users:password_reset', user_id=user_id) # Redrct For Further Prcss
        else:
            messages.error(
                request, f'We did not found any account this username.')                   

    return render(request, 'users/password_reset_confirm.html', context)

def password_reset(request, user_id):
    if request.method == 'POST':
        user = User.objects.get(id=user_id)
        profile = user.profile
        form = PasswordResetForm(request.POST)

        if form.is_valid():
            otp = form.cleaned_data.get('otp')
            new_password = form.cleaned_data.get('new_password')
            if otp == profile.otp and otp != 0:
                profile.otp = 0 # Reset OTP
                profile.save()
                user.set_password(new_password)
                user.save()
                authenticated_user = authenticate(username=user.username,
                                                  password=request.POST['new_password'])
                login(request, authenticated_user) # Login User With New Password               
                messages.success(
                request, f'Password has been resetted successfully.')
                return redirect('ncubook:index')
            else:            
                messages.error(
                request, f'Incorrect OTP! Please enter correct OTP')

        else:
            messages.error(
                request, f' Unable to reset password. Please correct the error below.')
    else:
        form = PasswordResetForm()
    
    context = {'form': form,}
    return render(request, 'users/password_reset.html', context)

@login_required
def edit_profile(request):
    """ Settings Page / Edit profile """
    profile = request.user.profile
    if request.method == 'POST':
        uform = UserUpdateForm(request.POST, instance=request.user)
        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if uform.is_valid() and pform.is_valid():
            uform.save()
            pform.save()

            # Detect Change In Verified Roll No (User Have To Verify Again!)
            if profile.roll != profile.verified_roll:
                profile.verified = False
                profile.save()

            messages.success(
                request, f'Profile has been updated successfully.')
            return redirect('users:profile', username=request.user.username)
        else:
            messages.error(
                request, f' Unable to update profile. Please correct the error below.')
    else:
        uform = UserUpdateForm(instance=request.user)
        pform = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'uform': uform,
        'pform': pform
    }

    return render(request, 'users/edit_profile.html', context)

@login_required
def verify_account_link(request):
    return render(request, 'users/verify_account_link.html')

@login_required
def verify_account(request):
    profile = request.user.profile

    if not profile.verified:
        # Generate & Save OTP
        raw_otp = random.randint(1000, 9999)
        profile.otp = raw_otp
        profile.save()

        # Send OTP Email
        recipient_list = [profile.email,]
        send_mail(
            "OTP for NCUbook roll no. verification.",
            f"OTP: {str(raw_otp)}",
            "NCUBook",
            recipient_list,
            fail_silently=True,
        )            

        if request.method == 'POST':
            form = AccountVerifyForm(request.POST)

            if form.is_valid():
                otp = form.cleaned_data.get('otp')
                if otp == profile.otp and otp != 0:
                    profile.verified = True
                    profile.otp = 0
                    profile.verified_roll = profile.roll # Verified Roll
                    profile.save()
                    messages.success(
                    request, f'Account has been verified successfully.')
                    return redirect('users:profile', username=profile.user.username)
                else:            
                    messages.error(
                    request, f'Incorrect OTP! Please enter correct OTP')

            else:
                messages.error(
                    request, f' Unable to verify account. Please correct the error below.')
        else:
            form = AccountVerifyForm()
        
        context = {'form': form,}

        return render(request, 'users/verify_account.html', context)
    else:
        return HttpResponse("Account is already verified")

@login_required
def profile(request, username):
    profile = Profile.objects.get(user__username=username)
    posts = Post.objects.filter(user=profile.user).order_by('-date_created')
    posts_count = posts.count()
    buddies_count = profile.buddies.all().count()
    context = {'profile_link_active': "link-active", 'profile': profile, 'posts': posts, 
    'posts_count': posts_count, 'buddies_count': buddies_count}
    return render(request, 'users/profile.html', context)

@login_required
def buddies(request, user):
    mutual_buddies_count = 0
    profile = Profile.objects.get(user__username=user)
    buddies = profile.buddies.all()
    print(buddies)
    buddies_count = buddies.count()

    my_buddies = request.user.profile.buddies.all()
    print(my_buddies)
    for my_buddy in my_buddies:
        if my_buddy in buddies:
            mutual_buddies_count += 1

    context = {'profile_link_active': "link-active", 'buddies': buddies, 'profile_user': profile.user.username,
     'buddies_count': buddies_count, 'mutual_buddies_count': mutual_buddies_count}
    return render(request, 'users/buddies.html', context)

@login_required
def remove_buddy(request, user_id):
    # Remove User From Buddies
    if request.method == "POST":
        user = request.user
        buddy = User.objects.get(id=user_id)
        response_data = {}

        # Remove Buddy From User's Buddies
        user.profile.buddies.remove(buddy)
        user.profile.save()
        # Remove User From Buddy's Buddies
        buddy.profile.buddies.remove(user)
        buddy.profile.save()
        response_data['status'] = 'done'
        return JsonResponse(response_data)
    else:
        raise Http404

def nav_brequests_count(request):
    count = 0
    if request.user.is_authenticated:
        count = BuddyRequest.objects.filter(receiver=request.user, seen=False).count()

    return {'nav_brequests_count':count}

@login_required
def send_request(request, user_id):

users/templates/users/buddies.html
{% extends 'ncubook/base.html' %} 
{% load static %}
{% block content %}

@{{profile_user}}:
{% if profile_user != request.user.username %}
<span class="is-pulled-right">
  <b>Mutual Buddies: {{mutual_buddies_count}}</b> 
</span>
{% endif %}


<!-- User Buddies Count -->
<nav class="level is-mobile">
  <!-- Left side -->
  <div class="level-left">
    <div class="level-item">
      <p class="title is-size-5 is-size-6-mobile">Buddies</p>
    </div>
  </div>

  <!-- Right side -->
  <div class="level-right">
    <p class="level-item"><b>{{buddies_count}}</b></p>
  </div>
</nav>
<hr>


<!-- Buddies -->
{% for user in buddies %}
{% include 'users/user-div.html' %}
{% endfor %}

<!-- Add Buddy JS -->
<script src="{% static 'js/FollowInterest.js' %}"></script>

{% endblock content %}

users/templates/users/buddy_requests.html
{% extends 'ncubook/base.html' %} 
{% load static %}
{% block content %}

<!-- User Buddies Count -->
<nav class="level is-mobile">
  <!-- Left side -->
  <div class="level-left">
    <div class="level-item">
      <p class="title is-size-5 is-size-6-mobile">
        Buddy Requests
      </p>
    </div>
  </div>

  <!-- Right side -->
  <div class="level-right">
    <p class="level-item"><b>{{buddy_requests_count}}</b></p>
  </div>
</nav>
<hr>

<!-- Buddies -->
{% for request in buddy_requests %}
<div class="card">
   <div class="card-content">
    	<div class="media">
		  <figure class="media-left">
		  	<a href="{% url 'users:profile' request.sender.username %}">
		    	<img src="{{request.sender.profile.profile_pic.url}}" class="user-profile-pic">
		  	</a>
		  </figure>
		  <div class="media-content">
		    <div class="content">
		      <p>
		        <a href="{% url 'users:profile' request.sender.username %}">
		        	<strong>{{request.sender.first_name}} {{request.sender.last_name}}</strong>
		        </a>
		        <br>
		        @{{request.sender.username}}
		        <br>
		        <small>{{request.date_created|timesince}} ago</small>
		      </p>
		    </div>
		  </div>
		  <button id="id_reject_request_button_{{request.id}}" class="button is-rounded"
			onclick="RejectRequest('{{request.id}}', this)"><b>Reject</b></button>
			&nbsp
		  <button id="id_accept_request_button_{{request.id}}" class="button is-rounded is-link"
			onclick="AcceptRequest('{{request.id}}', this)"><b>Accept</b></button>
  		</div>
   </div>
</div>
<br>
{% endfor %}

{% endblock content %}


users/templates/users/login_details.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page Header -->
<center>
  <p class="title is-size-4 is-size-5-mobile">Login Details</p>
  <hr class="page-header-hr">
</center>

<p class="title is-size-5 is-size-6-mobile has-text-centered">
  Last login: {{last_login|date:'h:i A - jS F Y'}}
</p>

<p class="help-text has-text-centered">
  Note: You have to login again in every 7 days.
</p>


{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page Header -->
<center>
  <p class="title is-size-4 is-size-5-mobile">Password Reset Confirm</p>
  <hr class="page-header-hr">
</center>

<p class="help-text has-text-centered">
  Enter your username to initiate password reset process for your account.<br><br>
</p>

<!-- Username Form -->
<div class="columns is-centered has-text-centered">
  <div class="column is-wider is-half-tablet">
    <div class="card">
      <div class="card-content">
        <form action="{% url 'users:password_reset_confirm' %}" method="POST" autocomplete="off">
          {% csrf_token %}

          <!-- Username -->
          <div class="field">
            <div class="control has-icons-left">
          <input class="input is-rounded" name="username" type="text" value="{{username}}" placeholder="Your Username">
              <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
            </div>
          </div>

          <!-- Submit Button -->
          <div class="field">
            <div class="control">
              <button class="button is-link is-rounded" name="action" type="submit">
                <b>Continue</b>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>


{% endblock content %}

users/templates/users/profile.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/profile.css' %}">

<div class="dropdown is-right is-pulled-right is-hoverable">
  <div class="dropdown-trigger">
    <a aria-haspopup="true" aria-controls="dropdown-menu4">
      <span class="icon is-small">
       <i class="fa fa-ellipsis-v"></i>
      </span>
    </a>
  </div>
  <div class="dropdown-menu" id="dropdown-menu4" role="menu">
    <div class="dropdown-content">
      <div class="dropdown-item">
      {% if profile.user != request.user %}
      {% if profile.user in request.user.profile.buddies.all %}
        <a id="id_remove_buddy_button_{{profile.user.id}}" class="dropdown-item"
          onclick="OpenModal('remove_buddy')">
          <span class="icon"><i class="fa fa-ban fa-lg"></i></span>
          <span><b>Remove Buddy</b></span>
        </a>
      {% else %}
        Hi! I'am {{profile.user.first_name}}
      {% endif %}
      {% else %}        
        <!-- Settings Links-->
        <a class="dropdown-item" href="{% url 'users:login_details' %}">
          <span class="icon"><i class="fa fa-lock fa-lg"></i></span>
          <span><b>Login Details</b></span>
        </a>

        <a class="dropdown-item"  href="{% url 'users:change_password' %}">
          <span class="icon"><i class="fa fa-key fa-lg"></i></span>
          <span><b>Change Password</b></span>
        </a>
      {% endif %}
      </div>
    </div>
  </div>
</div>
<br>

<div class="columns is-centered is-mobile">
<div class="column">
<!-- User Profile Pic --->
<center>
  <img style="width: 170px; height: 170px; border-radius: 50%; object-fit: cover;" src="{{profile.profile_pic.url}}">
</center>

<!-- Name & Username --->
<center>
  <p class="title">{{profile.user.first_name}} {{profile.user.last_name}}</p>
  <p class="subtitle">@{{profile.user.username}}</p>
</center>
<br>

      <center>
      {% if profile.user != request.user %}
      {% if profile.user in request.user.profile.buddies.all %}
      <button id="id_dm_button" onclick="OpenSendDM({{profile.user.id}})" class="button is-rounded is-link"
      ><b>Message</b></button>      
      {% elif profile.user in request.user.profile.requested.all %}
      <button id="id_add_buddy_button_{{profile.user.id}}" class="button is-rounded is-success"
      ><b>Request Sent</b></button> 
      {% else %}
      <button id="id_send_request_button_{{profile.user.id}}" class="button is-rounded is-link"
      onclick="SendRequest('{{profile.user.id}}', this)"><b>Add Buddy</b></button>          
      {% endif %}
      {% else %}
        <a href="{% url 'users:edit_profile' %}" class="button is-small"><b>Edit Profile</b></a>
      {% endif %}
      <br><br>
      </center>

    <!-- Remove Buddy Confirmation Modal -->
    <div id="modal_id_remove_buddy" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Remove Buddy</p>
          <button class="delete" onclick="CloseModal('remove_buddy')" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
          <p class="subtitle is-size-5 is-size-6-mobile">Do you really want to end this friendship?</p>
        </section>
        <footer class="modal-card-foot">
          <button class="button is-rounded is-fullwidth is-link"
          onclick="RemoveBuddy('{{profile.user.id}}')"><b>Remove Buddy</b></button>
          <button class="button is-rounded is-fullwidth" onclick="CloseModal('remove_buddy')"><b>Cancel</b></button>
        </footer>
      </div>
    </div>
    <!-- Remove Buddy Confirmation Modal -->

    <!-- DM Modal -->
    <div id="modal_id_dm" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Direct Message</p>
          <button class="delete" onclick="CloseModal('dm')" aria-label="close"></button>
        </header> 
        <section class="modal-card-body">
          <form class="is-disabled" id="id_dm_form" onsubmit="return false"> 
            <div class="columns is-mobile">
              <!-- Profile Pic -->  
              <div class="column is-narrow">
              <figure>
                <img id="id_dm_form_user_pic" src="{{request.user.profile.profile_pic.url}}" class="user-profile-pic">
              </figure>
            </div>               
            <!-- Body -->
            <div class="column">
              <textarea id="id_dm_form_textarea" class="textarea has-fixed-size" placeholder="Enter your message" maxlength="100" required></textarea>
              </div>
            </div>
          </form>
        </section>
        <footer class="modal-card-foot">
        <button id="id_dm_form_submit" class="button is-fullwidth is-rounded is-link" onclick="SendDM({{profile.user.id}})"><b>Send</b></button>
        </footer>
      </div>
    </div>
    <!-- End DM Modal -->
  </div>
  <div class="column">
    <br><br>
    <!-- User Buddies Count -->
    <nav class="level is-mobile"> 
      <!-- Left side -->
      <div class="level-left">
        <div class="level-item">
          <p class="subtitle">
            <span class="icon"><i class="fa fa-users"></i></span>
            Buddies: <strong>{{buddies_count}}</strong>
          </p>
        </div>
      </div>

      <!-- Right side -->
      <div class="level-right">

        <p class="level-item">
          <a href="{% url 'users:buddies' profile.user.username %}"><u>See</u></a>
        </p>
      </div>
    </nav>

    <!-- User Posts Count -->
    <p class="subtitle">
      <span class="icon"><i class="fa fa-list"></i></span>
      Posts: <strong id="id_post_count">{{posts_count}}</strong>
    </p>  
  </div>
</div>
<!-- User Information --->
<div class="card">
  <header class="card-header">
    <p class="card-header-title">Information</p>
  </header>

  <div class="card-content">
    Roll No: {{profile.roll}}

    {% if profile.verified %}
    <i title="Roll No is Verifed" style="color:blue" class="fa fa-check-circle"></i><br>
    {% else %}
    <br><a href="{% url 'users:verify_account_link' %}" class="help">Click here to verify your account.</a>
    {% endif %}

    Gender: {{profile.gender}}<br>

    Coarse: {{profile.coarse_branch}}<br>
    Year: {{profile.year}}<br>

    {% if profile.hometown %}
    Hometown: {{profile.hometown}}<br>
    {% endif %}

    {% if profile.interests %}
    Hometown: {{profile.interests}}<br>
    {% endif %}

    Birthday: {{profile.birthday|date:"jS F"}}<br>
    Joined NCUbook: {{profile.user.date_joined|date:"jS F Y"}}
  </div>
</div>
<br>
<!-- User Posts -->
{% for post in posts %}
{% include 'posts/post-div.html' %}
{% endfor %}

<script src="{% static 'js/OpenSendDM.js' %}"></script>
<script src="{% static 'js/SendDM.js' %}"></script> 

{% endblock content %}

users/templates/users/signup.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Sign up Form -->
<div class="columns is-centered has-text-centered">
  <div class="column is-half">
    <div class="card">
      <div class="card-content">
        <br>
        <img src="{% static 'images/logo-blue.png' %}" width="150" >
        <br><br>         
        <form role="form" method="post">
          {% csrf_token %}

          <!-- Name -->
          <div class="field">
            <div class="control has-icons-left has-icons-right">
              {{form.name}} 
              <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
            </div>

            <!-- Name Errors -->
            {% if form.name.errors %}
              <p class="help is-danger">
                <ul>
                  {% for error in form.name.errors %}
                    <li>
                      <strong style="color: red;">{{ error|escape }}</strong>
                    </li>
                  {% endfor %}
                </ul>
              </p>
            {% endif %}

          </div>

          <!-- Username -->
          <div class="field">
            <div class="control has-icons-left has-icons-right">
              {{form.username}}
              <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
            </div>

            <!-- Username Errors -->
            {% if form.username.errors %}
              <p class="help is-danger">
                <ul>
                  {% for error in form.username.errors %}
                    <li>
                      <strong style="color: red;">{{ error|escape }}</strong>
                    </li>
                  {% endfor %}
                </ul>
              </p>
            {% endif %}

          </div>

          <!-- Password -->
          <div class="field">
            <div class="control has-icons-left has-icons-right">
              {{form.password1}}
              <span class="icon is-small is-left"><i class="fa fa-key"></i></span>
            </div>

            <!-- Password errors -->
            {% if form.password1.errors %}
              <p class="help is-danger">
                <ul>
                  {% for error in form.password1.errors %}
                    <li>
                      <strong style="color: red;">{{ error|escape }}</strong>
                    </li>
                  {% endfor %}
                </ul>
              </p>
            {% endif %}

          </div>

          <!-- Submit Button -->
          <div class="field">
            <div class="control">
              <button class="button is-rounded is-fullwidth is-link" name="action" type="submit">
              <b>Sign Up</b>
              </button>
            </div>
          </div>
          <br>

          <!-- Agreement -->
          <p class="help" style="padding-bottom: 5px;">
            By clicking above Sign up button, you agree to our
            <a href="{% url 'ncubook:privacy' %}">Privacy</a>
            &
            <a href="{% url 'ncubook:terms' %}">Terms</a>
          </p>
          <br>

          <!-- Log in Link -->
          <p class="subtitle is-size-6 ">
            Already have an account?
            <a href="{% url 'ncubook:login' %}">Log In</a>
          </p>
          <br>
          
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer >
  <div class="content has-text-centered">

    <!-- Footer menu -->
    <p>
      <a href="{% url 'ncubook:about' %}">About | </a>
      <a href="{% url 'ncubook:contact' %}">Contact | </a>
      <a href="{% url 'ncubook:privacy' %}">Privacy | </a>
      <a href="{% url 'ncubook:terms' %}">Terms</a>
    </p>

    <!-- a Shikeb Khan production -->
    <p>a Shikeb Khan production<br>
    <!-- Footer copyright -->
    NCUbook © {% now "Y" %} </p>

  </div>
</footer>

{% endblock content %}

users/templates/users/verify_account_link.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page Header -->
<center>
  <p class="title is-size-4 is-size-5-mobile">Verify Account Link</p>
  <hr class="page-header-hr">
</center>

<p class="help-text has-text-centered">
  We will send an OTP on your NCU email adress.<br>
  Incase you do not recieve OTP then please contact admin for OTP.<br><br>

  <a href="{% url 'users:verify_account' %}" class="button is-link is-rounded"><b>Continue</b></a>
</p>



{% endblock content %}