posts/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Add Post
    path('add_post/', views.add_post, name='add_post'), 

    # Like Post
    path('like_post/<int:post_id>/', views.like_post),

    # Report Post
    path('report_post/<int:post_id>/', views.report_post),

    # Delete Post
    path('delete_post/<int:post_id>/', views.delete_post),

    # Post Comments Page
    path('post_comments/<int:post_id>/', views.post_comments, name='post_comments'), 

    # Report Comment
    path('report_comment/<int:comment_id>/', views.report_comment),

    # Add Comment
    path('add_comment/', views.add_comment), 

    # Delete Comment
    path('delete_comment/<int:comment_id>/', views.delete_comment),    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        # Khan Diary url config.
        path('', include(('ncubook.urls', 'ncubook'), namespace='ncubook')),

        # Users url config.
        path('', include(('users.urls', 'users'), namespace='users')),

        # Posts url config.
        path('', include(('posts.urls', 'posts'), namespace='posts')),

        # Messenger url config.
        path('', include(('messenger.urls', 'messenger'), namespace='messenger')),

        # Notifications url config.
        path('', include(('notifications.urls', 'notifications'), namespace='notifications')),

        # Admin url config
        path('admin/', admin.site.urls), 

        # Detect Timezone
        path('tz_detect/', include('tz_detect.urls')),
]

# Admin portal config.
admin.site.site_header = 'NCUbook Adminstration'
admin.site.index_title = 'Site Administration'
admin.site.site_title = "NCUbook - Admin"

users/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    # Sign Up Page    
    path('signup/', views.signup, name='signup'),

    # Password Reset Confirm
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),

    # Password Reset 
    path('password_reset/<int:user_id>/', views.password_reset, name='password_reset'),

    # Profile Page
    path('<str:username>/profile', views.profile, name='profile'), 

    # Buddies Page
    path('<str:user>/buddies', views.buddies, name='buddies'),

    # Remove Buddy 
    path('remove_buddy/<int:user_id>/', views.remove_buddy),

    # Send Buddy Request
    path('send_request/<int:user_id>/', views.send_request),

    # Accept Buddy Request
    path('accept_request/<int:request_id>/', views.accept_request),

    # Reject Buddy Request
    path('reject_request/<int:request_id>/', views.reject_request),

    # Buddy Requests Page
    path('buddy_requests', views.buddy_requests, name='buddy_requests'), 

    # Edit Profile Page
    path('edit_profile/', views.edit_profile, name='edit_profile'), 

    # Verify Account Link
    path('verify_account_link/', views.verify_account_link, name='verify_account_link'),

    # Verify Account 
    path('verify_account/', views.verify_account, name='verify_account'),

    # Login Details Page
    path('login_details/', views.login_details, name='login_details'),

    # Settings / Change Password Page
    path('settings/change_password/', views.change_password, name='change_password'),     
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from django.conf import settings
from PIL import Image

# Where Post Pic Will Store
def post_pic_dir_path(instance, filename):
    post_pic_name = 'user_data/{0}/post_pics/{1}'.format(instance.user.username,filename)
    full_path = os.path.join(settings.MEDIA_ROOT, post_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return post_pic_name

# Where Post PDF Will Store
def post_pdf_dir_path(instance, filename):
    post_pdf_name = 'user_data/{0}/post_pdfs/{1}'.format(instance.user.username,filename)
    full_path = os.path.join(settings.MEDIA_ROOT, post_pdf_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return post_pdf_name

# File Input Validation
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

def file_size(value): # add this to some file where you can import it from
    limit = 10 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 10 MB.')

class Post(models.Model):
    # User
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Main Content
    body = models.TextField(max_length=200)
    url = models.URLField(max_length=200, blank=True, null=True)
    pic = models.ImageField(upload_to=post_pic_dir_path, validators=[file_size], blank=True, null=True)
    pdf = models.FileField(upload_to=post_pdf_dir_path, validators=[file_size, FileExtensionValidator(allowed_extensions=["pdf"])], blank=True, null=True)

    # Meta Info
    likes = models.PositiveIntegerField(default=0)
    reported = models.BooleanField(default=False)

    # Date
    date_created = models.DateTimeField(auto_now_add=True, null=True)


    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs) # Save it here as image cmprss needed saved post

        if self.pic:
            # Compress Profile Pic 
            image = Image.open(self.pic.path)
            try:
              exif = image.info['exif']
            except KeyError:
              exif = None

            if exif != None: # Check If exif Is Not Empty          
                image.save(self.pic.path,quality=33,optimize=True, exif=exif)

    def __str__(self):
        return self.body[:50]

class Comment(models.Model):
    # User & Post
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    # Main Content
    body = models.TextField(max_length=100)

    # Meta Info
    reported = models.BooleanField(default=False)

    # Date
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.body[:50]

posts/forms.py

from django import forms
from django.core.exceptions import ValidationError
from .models import Post



class PostForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': "textarea has-fixed-size" ,'placeholder': "Share your thoughts with your NCU buddies", 'rows': "5", 'autocomplete': 'off', 'maxlength': "200", 'autofocus': 'on',}))

    url = forms.URLField(widget=forms.TextInput(attrs={'class': 'input is-small is-rounded', 'placeholder': "URL"}), required=False)

    pic = forms.ImageField(widget=forms.FileInput(attrs={'class': 'file is-link'}), required=False) 

    pdf = forms.FileField(widget=forms.FileInput(attrs={'class': 'file is-link', 'accept': '.pdf'}), required=False)

    class Meta:
        model = Post
        fields = ['body', 'url', 'pic', 'pdf']

    def clean(self):
        # data from the form is fetched using super function
        super(PostForm, self).clean()
        # return any errors if found.
        return self.cleaned_data




posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from .models import Post, Comment
from notifications.models import Notification
from .forms import PostForm
from django.http import HttpResponse, JsonResponse, Http404

@login_required
def add_post(request):
    user = request.user
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # Keep Only 5 Posts
            posts = Post.objects.filter(user=user)
            posts_count = posts.count()
            if posts_count >= 5:
                post = Post.objects.filter(user=user).first()
                post.delete()

            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(
                request, 'Posted successfully.')
        else:
            messages.error(
                request, 'Posted unsuccessfully.')
        return redirect('ncubook:index')

@login_required
def like_post(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(id=post_id)
        preview = post.body[:70] #For noti.
        profile = request.user.profile

        # Like
        if post not in profile.liked_posts.all():
            post.likes += 1
            post.save() 
            profile.liked_posts.add(post)
            profile.save()

            # Add Notification
            if post.user != request.user:
                Notification.objects.create(post=post, sender=request.user, user=post.user, preview=preview, notification_type=1)

            
        # Unlike
        else:
            post.likes -= 1
            post.save() 
            profile.liked_posts.remove(post)
            profile.save()

            # Delete Notification
            if post.user != request.user:
                noti = Notification.objects.filter(post=post, sender=request.user, user=post.user, preview=preview, notification_type=1)
                noti.delete()

        return JsonResponse({'status': "Success"})
    else:
        raise Http404

@login_required
def report_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == "POST" and post.user != request.user:
        post.reported = True
        post.save() 
        return JsonResponse({'status': "Success"})
    else:
        raise Http404

@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == "POST" and post.user == request.user:
        post.delete() 
        return JsonResponse({'status': "Success"})
    else:
        raise Http404

@login_required
def post_comments(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post).order_by('-date_created')
    context = {'post': post, 'comments': comments}
    return render(request, 'posts/post_comments.html', context)

@login_required
def add_comment(request):
    if request.method == "POST":

        # Collect Data From Ajax Form
        post_id = request.POST.get('post_id') 
        body = request.POST.get('body')
        post = get_object_or_404(Post, id=post_id)

        # Keep Only 100 Comments
        comments = Comment.objects.filter(post=post)
        comments_count = comments.count()
        if comments_count >= 100:
            comment = Comment.objects.filter(post=post).first()
            comment.delete()

        # Create Comment
        Comment.objects.create(post=post, user=request.user, body=body[:100])                    

        # Add Notification
        if post.user != request.user:
            preview = body[:70] #For noti.
            Notification.objects.create(post=post, sender=request.user, user=post.user, preview=preview, notification_type=2)

        return JsonResponse({'status': "Success"})
    else:
        raise Http404

@login_required
def report_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == "POST" and comment.user != request.user:
        comment.reported = True
        comment.save() 
        return JsonResponse({'status': "Success"})
    else:
        raise Http404

@login_required
def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == "POST" and comment.user == request.user:
        comment.delete()

        # Delete Notification
        if post.user != request.user:
            noti = Notification.objects.filter(post=post, sender=request.user, user=post.user, preview=preview, notification_type=2)
            noti.delete() 
                    
        return JsonResponse({'status': "Success"})
    else:
        raise Http404




posts/templates/posts/post-div.html
{% load static %}

<!-- Post -->
<div class="card" id="id_post_div_{{post.id}}">
  <div class="card-content">
  <div class="media">
    <div class="media-left">
      <figure>
        <a href="{% url 'users:profile' post.user.username %}">
          <img src="{{post.user.profile.profile_pic.url}}" class="card-profile-pic">
        </a>
      </figure>
    </div> 
    <!-- User & Date-->
    <div class="media-content">
      <p class="title is-size-6"><a href="{% url 'users:profile' post.user.username %}">{{post.user.first_name}} {{post.user.last_name}}</a></p>
      <p class="subtitle is-6">{{post.date_created|date:"d M Y"}}</p>
    </div>

    <!-- Three Dot Menu -->
    <div id="menu_id_{{post.id}}" class="dropdown is-right">
      <div id="menu_trigger_id_{{post.id}}" class="dropdown-trigger" onclick="OpenThreeDotMenu({{post.id}})">
        <i class="is-pulled-right fa fa-ellipsis-v"></i>
      </div>
      <div class="dropdown-menu" id="dropdown-menu1" role="menu">
        <div class="dropdown-content">
          <div class="dropdown-item">
            {% if post.user == request.user %}
            <a class="dropdown-item" onclick="DeletePost({{post.id}})">
              <span class="icon"><i class="fa fa-trash"></i></span>
              Delete
            </a>
            {% else %}
            {% if not post.reported %}
            <a id="id_post_report_button_{{post.id}}" class="dropdown-item" onclick="ReportPost({{post.id}})">Report</a>
            {% else %}
            <a class="dropdown-item">Post Reported</a>            
            {% endif %}
            {% endif %}         
          </div>
        </div>
      </div>
    </div>     
  </div>

  {% if post.url %}
  <!-- Post Link -->
  <span class="icon-text has-text-info">
    <span class="icon">
     <i class="fa fa-link"></i>
    </span>
    <span>
      <a href="{{post.url}}" target="_blank">Go To Attached Link</a>
    </span>
  </span>
  {% endif %}

  {% if post.pic %}
  <!-- Post Pic -->
  <div class="card-image">
    <center>
      <figure>
        <img src="{{post.pic.url}}" class="post-pic">
      </figure>
    </center>
  </div>
  {% endif %}

  {% if post.pdf %}
  <!-- Post PDF -->
  <span class="icon-text has-text-danger">
    <span class="icon">
     <i class="fa fa-sticky-note"></i>
    </span>
    <span>
      <a href="{{post.pdf.url}}" download>Download Attached PDF</a>
    </span>
  </span>
  {% endif %}

  <!-- Content -->
  <p class="subtitle is-size-6-mobile">
  {{post.body}}
  </p>
  </div>

  <!-- Likes, Comments-->
  <div class="card">
    <footer class="card-footer">
      {% if post not in request.user.profile.liked_posts.all  %}
      <a class="card-footer-item"> 
        <i id="post_like_button_{{post.id}}" class="fa fa-thumbs-o-up fa-lg" onclick="LikePost('{{post.id}}')"></i>&nbsp
        <span id="post_likes_count_{{post.id}}">{{post.likes}}</span>
      </a>
      {% else %}
      <a class="card-footer-item"> 
        <i id="post_unlike_button_{{post.id}}" class="fa fa-thumbs-up fa-lg" onclick="LikePost('{{post.id}}')"></i>&nbsp
        <span id="post_likes_count_{{post.id}}">{{post.likes}}</span>
      </a>      
      {% endif %}
      <a href="{% url 'posts:post_comments' post.id %}" class="card-footer-item">
        <i class="fa fa-comment fa-lg"></i>&nbsp
        <span id="id_comment_count">{{post.comment_set.all.count}}</span>
      </a>      
    </footer>
  </div>
</div>
<br id="id_post_div_br_{{post.id}}">

posts/templates/posts/post_comments.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Post -->
{% include 'posts/post-div.html' %}

<!-- Comment Form -->
<br>
<form class="is-disabled" id="id_comment_form" onsubmit="return false"> 
  <div class="columns is-mobile">
    <!-- Profile Pic -->  
    <div class="column is-narrow">
    <figure>
      <img id="id_comment_form_user_pic" src="{{request.user.profile.profile_pic.url}}" class="user-profile-pic">
    </figure>
  </div> 

  <!-- Body -->
  <div class="column">
    <textarea id="id_comment_form_textarea" class="textarea has-fixed-size" placeholder="Enter your comment" maxlength="100" required  autofocus></textarea>
    </div>
  </div>

  <button id="id_comment_form_submit" class="button is-pulled-right is-rounded is-link" onclick="AddComment({{post.id}})"><b>Add</b></button>
  <br>
  <br>
</form>

<!-- Comments -->
{% for comment in comments %}
<article class="media" id="id_comment_div_{{comment.id}}">
  <figure class="media-left">
    <img src="{{comment.user.profile.profile_pic.url}}" class="card-profile-pic">
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <a><strong>{{comment.user.first_name}} {{comment.user.last_name}}</strong></a>
        <br>{{comment.body}}<br>
        <small>{{comment.date_created|timesince}} ago</small>
        <span class="is-pulled-right">
        {% if comment.user == request.user %}
        <a onclick="DeleteComment({{comment.id}})">[Delete]</a>
        {% else %}
        {% if not comment.reported %}
        <a id="id_comment_report_button_{{comment.id}}" onclick="ReportComment({{comment.id}})">[Report]</a> 
        {% else %} [Reported] {% endif %}
        {% endif %}
        </span>
      </p>
    </div>
  </div>
</article>
{% endfor %}

<script src="{% static 'js/AddComment.js' %}"></script>
<script src="{% static 'js/ReportComment.js' %}"></script> 
<script src="{% static 'js/DeleteComment.js' %}"></script> 

{% endblock content %}