notifications/urls.py
from django.urls import path
from .import views

urlpatterns = [

    # NotificationsPage
    path('notifications/', views.notifications, name='notifications'),
    
    #Clear notifications.
    path('clear_notifications/', views.clear_notifications, name='clear_notifications'),
]

posts/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Add Post
    path('add_post/', views.add_post, name='add_post'), 

    # Like Post
    path('like_post/<int:post_id>/', views.like_post),

    # Report Post
    path('report_post/<int:post_id>/', views.report_post),

    # Delete Post
    path('delete_post/<int:post_id>/', views.delete_post),

    # Post Comments Page
    path('post_comments/<int:post_id>/', views.post_comments, name='post_comments'), 

    # Report Comment
    path('report_comment/<int:comment_id>/', views.report_comment),

    # Add Comment
    path('add_comment/', views.add_comment), 

    # Delete Comment
    path('delete_comment/<int:comment_id>/', views.delete_comment),    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        # Khan Diary url config.
        path('', include(('ncubook.urls', 'ncubook'), namespace='ncubook')),

        # Users url config.
        path('', include(('users.urls', 'users'), namespace='users')),

        # Posts url config.
        path('', include(('posts.urls', 'posts'), namespace='posts')),

        # Messenger url config.
        path('', include(('messenger.urls', 'messenger'), namespace='messenger')),

        # Notifications url config.
        path('', include(('notifications.urls', 'notifications'), namespace='notifications')),

        # Admin url config
        path('admin/', admin.site.urls), 

        # Detect Timezone
        path('tz_detect/', include('tz_detect.urls')),
]

# Admin portal config.
admin.site.site_header = 'NCUbook Adminstration'
admin.site.index_title = 'Site Administration'
admin.site.site_title = "NCUbook - Admin"

users/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    # Sign Up Page    
    path('signup/', views.signup, name='signup'),

    # Password Reset Confirm
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),

    # Password Reset 
    path('password_reset/<int:user_id>/', views.password_reset, name='password_reset'),

    # Profile Page
    path('<str:username>/profile', views.profile, name='profile'), 

    # Buddies Page
    path('<str:user>/buddies', views.buddies, name='buddies'),

    # Remove Buddy 
    path('remove_buddy/<int:user_id>/', views.remove_buddy),

    # Send Buddy Request
    path('send_request/<int:user_id>/', views.send_request),

    # Accept Buddy Request
    path('accept_request/<int:request_id>/', views.accept_request),

    # Reject Buddy Request
    path('reject_request/<int:request_id>/', views.reject_request),

    # Buddy Requests Page
    path('buddy_requests', views.buddy_requests, name='buddy_requests'), 

    # Edit Profile Page
    path('edit_profile/', views.edit_profile, name='edit_profile'), 

    # Verify Account Link
    path('verify_account_link/', views.verify_account_link, name='verify_account_link'),

    # Verify Account 
    path('verify_account/', views.verify_account, name='verify_account'),

    # Login Details Page
    path('login_details/', views.login_details, name='login_details'),

    # Settings / Change Password Page
    path('settings/change_password/', views.change_password, name='change_password'),     
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

notifications/models.py
from django.db import models
from django.contrib.auth.models import User

class Notification(models.Model):
    NOTIFICATION_TYPES = ((1,'Like Post'),(2,'Add Comment'),(3,'Accepted Buddy Request'))

    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_from_user", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_to_user")
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    preview = models.CharField(max_length=100, null=True, blank=True)
    is_seen = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

notifications/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Notification
from django.contrib import messages

def nav_notifications_count(request):
    """ Show unread notifications count on navbar. """
    nav_notifications_count = 0
    if request.user.is_authenticated:
        nav_notifications_count = Notification.objects.filter(user=request.user, is_seen=False).count()

    return {'nav_notifications_count': nav_notifications_count}
    

@login_required
def notifications(request):
    """ Show Notifications """
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date_created')
    Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

    notifications_count = notifications.count()

    context = {
    'notifications': notifications, 'notifications_count': notifications_count,
    }

    return render(request, 'notifications/notifications.html', context)


@login_required
def clear_notifications(request):
    """Clear all notifications at once """
    if request.method == "POST":
        user = request.user
        notifications = Notification.objects.filter(user=user, is_seen=True)
        notifications.delete()
        messages.success(request, f'All notifications has been cleared successfully.')
        return redirect('notifications:notifications')
    else:
        Http404    


notifications/templates/notifications/notifications.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<p class="title is-size-5 is-size-6-mobile">Notifications: 0
	{% if notifications_count != 0 %}
	<span class="is-pulled-right">
		<button class="button is-small is-rounded is-link" type="submit" onclick="OpenModal('clear_notifications')" >
			<b>Clear all</b>
	    </button>
	</span>
	{% endif %}
</p>
<hr>

<!-- Notifications -->
<div class="columns is-centered">
 	<div class="column is-half is-wider">
		{% for notification in notifications %}

      {% if notification.notification_type == 1 %}
      <div class="notification">
      <div class="media">
		  <figure class="media-left">
		  	<a href="{% url 'users:profile' notification.sender.username %}">
		    	<img src="{{notification.sender.profile.profile_pic.url}}" class="user-profile-pic">
		  	</a>
		  </figure>
		  <div class="media-content">      	
        <!-- From -->
        <a href="{% url 'users:profile' notification.sender.username %}" style="text-decoration: none;"><strong>{{notification.sender.first_name}} {{notification.sender.last_name}}</strong>@{{notification.sender}}</a>
        <br>
        <!-- Subject -->
        <span class="icon-text">
          <span class="icon"><i class="fa fa-thumbs-up"></i></span>
          <span>Liked your post</span>
        </span>
        <br>
        <!-- Content -->
        <p><small><a href="{% url 'posts:post_comments' notification.post.id %}">"{{notification.preview|truncatechars:69}}"</a></small></p>
        <!-- Time Since-->
        <strong><small>{{notification.date_created|timesince}} ago</small></strong>
      </div>
    </div>
    </div>
      {% endif %}


      {% if notification.notification_type == 2 %}
      <div class="notification">
      <div class="media">
		  <figure class="media-left">
		  	<a href="{% url 'users:profile' notification.sender.username %}">
		    	<img src="{{notification.sender.profile.profile_pic.url}}" class="user-profile-pic">
		  	</a>
		  </figure>
		  <div class="media-content">       	
        <!-- From -->
        <a href="{% url 'users:profile' notification.sender %}" style="text-decoration: none;"><strong>{{notification.sender.first_name}} {{notification.sender.last_name}}</strong>@{{notification.sender}}</a>
        <br>
        <!-- Subject -->
        <span class="icon-text">
          <span class="icon"><i class="fa fa-comment"></i></span>
          <span>Commented on your post</span>
        </span>
        <br>
        <!-- Content -->
        <p><small><a href="{% url 'posts:post_comments' notification.post.id %}">"{{notification.preview|truncatechars:69}}"</a></small></p>
        <!-- Time Since-->
        <strong><small>{{notification.date_created|timesince}} ago</small></strong>
      	</div>
		   </div>
		  </div>
      {% endif %}

      {% if notification.notification_type == 3 %}
      <div class="notification">
      <div class="media">
		  <figure class="media-left">
		  	<a href="{% url 'users:profile' notification.sender.username %}">
		    	<img src="{{notification.sender.profile.profile_pic.url}}" class="user-profile-pic">
		  	</a>
		  </figure>
		  <div class="media-content"> 
        <!-- From -->
        <a href="{% url 'users:profile' notification.sender %}" style="text-decoration: none;"><strong>{{notification.sender.first_name}} {{notification.sender.last_name}}</strong>@{{notification.sender}}
        </a>
        <br>
        <!-- Subject -->
        <span class="icon-text">
          <span class="icon"><i class="fa fa-user-plus"></i></span>
          <span>Accepted your buddy request</span>
        </span>
        <br>
        <!-- Time Since-->
        <strong><small>{{notification.date_created|timesince}} ago</small></strong>
      </div>
    </div>
  </div>
      {% endif %}
    {% endfor %}
	  </div>
		</div>
	
<!-- End Notifications -->

<!-- Clear Notifications Confirmation Modal -->
<div id="modal_id_clear_notifications" class="modal">
<div class="modal-background"></div>
<div class="modal-card">
  <header class="modal-card-head">
    <p class="modal-card-title">Clear Notifications</p>
    <button class="delete" onclick="CloseModal('clear_notifications')" aria-label="close"></button>
  </header>
  <section class="modal-card-body">
    <p class="subtitle is-size-5 is-size-6-mobile">Do you really want to delete all notifications?</p>
  </section>
  <footer class="modal-card-foot">
	  <!-- Clear All Notifications Form -->
		<form style="width:100%;" action="{% url 'notifications:clear_notifications' %}" method="POST" >
		  {% csrf_token %}  
		<button class="button is-rounded is-fullwidth is-link" type="submit"><b>Clear all</b></button>
		</form>
		<button class="button is-rounded is-fullwidth" onclick="CloseModal('clear_notifications')"><b>Cancel</b></button>
	</footer>
</div>
</div>
<!-- Clear Notifications Confirmation Modal -->

{% endblock content %}