messenger/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [
    # Direct Messages Page
    path('inbox', views.inbox, name='inbox'), 

    # Send DM
    path('send_dm/', views.send_dm),

    # Delete DM
    path('delete_dm/<int:dm_id>/', views.delete_dm, name='delete_dm'),
]

ncubook/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Log In Page
    path('login/', authViews.LoginView.as_view(
        template_name='ncubook/login.html'), name='login'),
    
    # Home Page
    path('', views.index, name='index'), 
    
    # Search
    path('search/', views.search, name='search'),

    # Search By Coarse Branch
    path('search/<str:coarse_branch>/', views.search_by_coarse_branch, name='search_by_coarse_branch'),

    # Privacy Policy  Page 
    path('privacy/', views.privacy, name='privacy'),

    # Terms & Conditions  Page
    path('terms/', views.terms, name='terms'),

    # About us Page
    path('about/', views.about, name='about'),

    # Contact us Page
    path('contact/', views.contact, name='contact'),
        
    # Log Out Page
    path('logout/', views.logout, name='logout'),    
]

notifications/urls.py
from django.urls import path
from .import views

urlpatterns = [

    # NotificationsPage
    path('notifications/', views.notifications, name='notifications'),
    
    #Clear notifications.
    path('clear_notifications/', views.clear_notifications, name='clear_notifications'),
]

posts/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views

urlpatterns = [

    # Add Post
    path('add_post/', views.add_post, name='add_post'), 

    # Like Post
    path('like_post/<int:post_id>/', views.like_post),

    # Report Post
    path('report_post/<int:post_id>/', views.report_post),

    # Delete Post
    path('delete_post/<int:post_id>/', views.delete_post),

    # Post Comments Page
    path('post_comments/<int:post_id>/', views.post_comments, name='post_comments'), 

    # Report Comment
    path('report_comment/<int:comment_id>/', views.report_comment),

    # Add Comment
    path('add_comment/', views.add_comment), 

    # Delete Comment
    path('delete_comment/<int:comment_id>/', views.delete_comment),    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        # Khan Diary url config.
        path('', include(('ncubook.urls', 'ncubook'), namespace='ncubook')),

        # Users url config.
        path('', include(('users.urls', 'users'), namespace='users')),

        # Posts url config.
        path('', include(('posts.urls', 'posts'), namespace='posts')),

        # Messenger url config.
        path('', include(('messenger.urls', 'messenger'), namespace='messenger')),

        # Notifications url config.
        path('', include(('notifications.urls', 'notifications'), namespace='notifications')),

        # Admin url config
        path('admin/', admin.site.urls), 

        # Detect Timezone
        path('tz_detect/', include('tz_detect.urls')),
]

# Admin portal config.
admin.site.site_header = 'NCUbook Adminstration'
admin.site.index_title = 'Site Administration'
admin.site.site_title = "NCUbook - Admin"

users/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    # Sign Up Page    
    path('signup/', views.signup, name='signup'),

    # Password Reset Confirm
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),

    # Password Reset 
    path('password_reset/<int:user_id>/', views.password_reset, name='password_reset'),

    # Profile Page
    path('<str:username>/profile', views.profile, name='profile'), 

    # Buddies Page
    path('<str:user>/buddies', views.buddies, name='buddies'),

    # Remove Buddy 
    path('remove_buddy/<int:user_id>/', views.remove_buddy),

    # Send Buddy Request
    path('send_request/<int:user_id>/', views.send_request),

    # Accept Buddy Request
    path('accept_request/<int:request_id>/', views.accept_request),

    # Reject Buddy Request
    path('reject_request/<int:request_id>/', views.reject_request),

    # Buddy Requests Page
    path('buddy_requests', views.buddy_requests, name='buddy_requests'), 

    # Edit Profile Page
    path('edit_profile/', views.edit_profile, name='edit_profile'), 

    # Verify Account Link
    path('verify_account_link/', views.verify_account_link, name='verify_account_link'),

    # Verify Account 
    path('verify_account/', views.verify_account, name='verify_account'),

    # Login Details Page
    path('login_details/', views.login_details, name='login_details'),

    # Settings / Change Password Page
    path('settings/change_password/', views.change_password, name='change_password'),     
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ncubook/models.py
from django.db import models

class Announcement(models.Model):
    body = models.CharField(max_length=150)
    def __str__(self):
        return str(self.body) 

    class Meta:
         verbose_name_plural = "Announcement"

ncubook/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Announcement
from users.models import CoarseBranch
from posts.models import Post
from posts.forms import PostForm
from django.contrib.auth.models import User
from django.contrib.auth import logout as django_logout
from django.contrib import messages
from django.http import Http404

@login_required
def index(request):
    buddies = request.user.profile.buddies.all()
    
    announcement = Announcement.objects.last()
    if announcement:
        announcement_body = announcement.body
    else:
        announcement_body = "Welcome to NCUbook"
        
    posts = Post.objects.filter(user__in=list(buddies)).order_by('-date_created')[:100]
    form = PostForm()
    context = {'index_link_active': "link-active", 'announcement': announcement.body, 'posts': posts, 'form': form}
    return render(request, 'ncubook/index.html', context)

@login_required
def search(request):
    coarse_branches = CoarseBranch.objects.all()            
    context = {'search_link_active': "link-active", 'coarse_branches': coarse_branches}     
    if request.method == "POST":
        query = request.POST.get("q")
        query = query.lstrip(" ")
        query = query.rstrip(" ")
        first_name = query.split(" ")
        if len(query) > 1:
            users = User.objects.filter(profile__roll__icontains=query).order_by('-date_joined') | \
                    User.objects.filter(username__icontains=query).order_by('-date_joined') | \
                    User.objects.filter(first_name__icontains=first_name[0]).order_by('-date_joined') | \
                    User.objects.filter(last_name__icontains=query).order_by('-date_joined')
            context['query'] = str(query)        
            context['users'] = users
    return render(request, 'ncubook/search.html', context)

@login_required
def search_by_coarse_branch(request, coarse_branch):
    coarse_branch = coarse_branch
    coarse_branches = CoarseBranch.objects.all()
    users = User.objects.filter(profile__coarse_branch__title=coarse_branch).order_by('-date_joined')
    context = {'search_link_active': "link-active", 'coarse_branches': coarse_branches, 'users': users}
    return render(request, 'ncubook/search.html', context)

def privacy(request):
    """Privacy Policy page"""
    return render(request, 'ncubook/privacy.html')

def terms(request):
    """Terms & Conditions page"""
    return render(request, 'ncubook/terms.html')

def about(request):
    """About us page"""
    return render(request, 'ncubook/about.html')

def contact(request):
    """Contact us page (with message functionality)"""
    return render(request, 'ncubook/contact.html')

def logout(request):
    if request.user.is_authenticated:
        django_logout(request)
        return redirect('ncubook:login')
    else:
        raise Http404    

ncubook/templates/ncubook/about.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page header -->
<center>
  <p class="title is-size-4 is-size-5-mobile">About us</p>
  <hr class="page-header-hr">
</center>

<!-- About Us Content -->
<div class="columns is-centered">
  <div class="column  is-three-quarters">

    <!-- Heading 1 -->
    <p class="title is-size-5">The Project</p>
    <p class="subtitle" id="the-project-sub">
      NCUbook is an online directory that connects students through social network at <img src="{% static 'images/ncu-icon.png' %}" width="20" > <b>Your University</b>.<br><br>
      You can use NCUbook to: <br>
        ● Search students at your university <br>
        ● Find out who are in your coarse <br>
        ● Know more information about a students via his/her profile <br>   
        ● See who are your buddies' buddies <br>
        ● Share Thoughts, Pics, Links, PDFs with your buddies <br>
        ● Directly send messages to your buddies
    </p>

    <br>

    <!-- Heading 2 -->
    <p class="title is-size-5">The People</p>
    <p class="subtitle" id="the-people-sub">Designed & Developed by Shikeb Khan</p>

  </div>
</div>

<center>
  .......................<br>
  Made with ❤️ in India
</center>

{% endblock content %}

ncubook/templates/ncubook/base.html
{% load static %}
{% load tz_detect %}
{% tz_detect %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NCUbook: NCU ka Apna Social Network!</title>
    <link rel="icon" href="{% static 'images/favicon.png' %}">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/social_network.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- End CSS -->
  </head>
 
  <body>
    {% if user.is_authenticated %}
    <!--Top Nav Bar -->
    <nav class="navbar is-fixed-top is-link has-shadow" role="navigation" aria-label="main navigation">
      <!-- Top Nav Icon -->
      <div class="navbar-item navbar-logo-div">
        <center>
        <img src="{% static 'images/logo.png' %}" width="150" >   
        </center>   
      </div>
      <!-- End Top Nav Icon -->  

      <!-- Top Nav Logo -->     
      <div class="navbar-brand is-inline-block">
      <span class="navbar-item is-inline-block">
        <img src="{% static 'images/icon.png' %}" width="28" height="28">
      </span>     
      </div>
      <!-- End Top Nav Logo -->

      <!-- Top Nav Menu Left -->
      <div class="navbar-menu">
      <a href="{% url 'ncubook:index' %}" class="navbar-item is-inline-block {{index_link_active}}">
        <i class="fa fa-home fa-lg" ></i> Home
      </a>

      <a href="{% url 'ncubook:search' %}" class="navbar-item is-inline-block {{search_link_active}}">
        <i class="fa fa-search fa-lg" ></i> Search
      </a>

      <a href="{% url 'messenger:inbox' %}" class="navbar-item is-inline-block {{inbox_link_active}}">
        <i class="fa fa-comments fa-lg" ></i>
          Inbox
          {% if nav_dms_count %}
          <span class="tag is-rounded is-danger">{{nav_dms_count}}</span>
          {% endif %}
      </a>


      <a href="{% url 'users:profile' request.user.username %}" class="navbar-item is-inline-block {{profile_link_active}}">
        <i class="fa fa-user fa-lg" ></i> {{request.user.first_name}}
      </a>

      <!-- End Records Dropdown Top -->

      </div>
      <!-- End Top Nav Menu Left -->

      <!-- Top Nav Menu Right -->
      <div class="navbar-right">
        <a class="navbar-item is-inline-block {{buddy_requests_link_active}}" href="{% url 'users:buddy_requests' %}">
          {% if nav_brequests_count %}
          <span class="tag is-rounded is-danger">{{nav_brequests_count}}</span>
          {% else %}
          <i class="fa fa-users fa-lg"></i>
          {% endif %}
          <span class="is-hidden-touch">Buddy Requests</span>                
        </a>

        <a class="navbar-item is-inline-block {{notifications_link_active}}" href="{% url 'notifications:notifications' %}">
          {% if nav_notifications_count %}
          <span class="tag is-rounded is-danger">{{nav_notifications_count}}</span>
          {% else %}
          <i class="fa fa-bell fa-lg"></i>
          {% endif %}
          <span class="is-hidden-touch">Notifications</span>                
        </a>       

        {% if user.is_authenticated %}
        <a class="navbar-item is-inline-block" onclick="OpenModal('logout')">
          <i class="fa fa-power-off fa-lg"></i>
          <span class="is-hidden-touch">Log Out</span>
        </a>
        {% endif %}

      </div>
      <!-- EndTop Nav Menu Right -->            
    </nav>
    <!-- End Top Nav Bar -->
    {% endif %}

   <!-- ##### Content ##### -->
    <section class="section">
      <div class="container">
        <!-- Noti Messages -->
        {% if messages %}
          {% for message in messages %}
            <article class="message is-{{message.tags}}">
              <div class="message-body">
                {{message}}
              </div>
            </article>
          {% endfor %}
        {% endif %}
        <!-- End Noti Messages -->

        <!-- Block Content -->
        <div class="columns is-centered">
          <div id="body-column" class="column is-two-thirds">

            {% block content %}{% endblock content %}
          </div>
        </div>
        <!-- End Block Content -->
      </div>

    </section>
    <!-- ##### End Content ##### -->

    {% if user.is_authenticated %}
    <!-- Bottom Nav Bar -->
    <nav class="navbar has-shadow is-fixed-bottom is-hidden-desktop" role="navigation">
      <!-- Bottom Nav Menu -->
      <div class="navbar-brand">
          <a href="{% url 'ncubook:index' %}"
             class="navbar-item is-expanded is-block has-text-centered {{index_link_active}}">
             <i class="fa fa-home fa-lg"></i>
             <p class="is-size-7">Home</p>
          </a>

          <a href="{% url 'ncubook:search' %}"
             class="navbar-item is-expanded is-block has-text-centered {{search_link_active}}">
             <i class="fa fa-search fa-lg"></i>
             <p class="is-size-7">Search</p>
          </a>

          <a href="{% url 'messenger:inbox' %}"
             class="navbar-item is-expanded is-block has-text-centered {{community_link_active}}">
             <i class="fa fa-comments fa-lg"></i>
             <p class="is-size-7">
              {% if nav_dms_count %}
              <span class="tag is-rounded is-danger">{{nav_dms_count}}</span>
              {% else %}
              Inbox
              {% endif %}
             </p>
          </a>


          <a href="{% url 'users:profile' request.user.username %}"
             class="navbar-item is-expanded is-block has-text-centered {{profile_link_active}}">
             <i class="fa fa-user fa-lg"></i>
             <p class="is-size-7">{{request.user.first_name}}</p>
          </a>

          <!-- End Records Dropdown Bottom -->
      </div>
      <!-- End Bottom Nav Menu -->
    </nav>
    <!-- End Bottom Nav Bar -->
    {% endif %}

    <!-- Logout Confirmation Modal -->
    <div id="modal_id_logout" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Log Out</p>
          <button class="delete" onclick="CloseModal('logout')" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
          <p class="subtitle is-size-5 is-size-6-mobile">Do you really want to Log Out?</p>
        </section>
        <footer class="modal-card-foot">
          <a href="{% url 'ncubook:logout' %}" class="button is-rounded is-fullwidth is-link"><b>Log Out</b></a>
          <button class="button is-rounded is-fullwidth" onclick="CloseModal('logout')"><b>Cancel</b></button>
        </footer>
      </div>
    </div>
    <!-- End Logout Confirmation Modal -->

    <!-- JS Scripts -->
    <script src="https://use.fontawesome.com/3a15d2b693.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>    
    <script src="{% static 'js/csrf.js' %}"></script>
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/Modal.js' %}"></script> 
    <script src="{% static 'js/ThreeDotMenu.js' %}"></script>
    <script src="{% static 'js/LikePost.js' %}"></script>
    <script src="{% static 'js/ReportPost.js' %}"></script>
    <script src="{% static 'js/DeletePost.js' %}"></script>   
    <script src="{% static 'js/BuddyRequest.js' %}"></script>
    <script src="{% static 'js/RemoveBuddy.js' %}"></script>         
    <!-- End JS Scripts -->
  </body>
</html>

ncubook/templates/ncubook/contact.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}


<!-- Page Header -->
<center>
  <p class="title is-size-4 is-size-5-mobile">Contact us</p>
  <hr class="page-header-hr">
</center>

<!-- A Message To User -->
<center>
	<p class="subtitle is-5">Any buisness, feedback, complain or message</p>
	<p class="subtitle is-5">Mail us at: 
	<a>samplemail@samplemail.com</a>
	</p>
	<br>
</center>


{% endblock content %}

ncubook/templates/ncubook/index.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/index.css' %}">

<!-- Announcement Strip -->
<marquee class="announcement">"{{announcement}}"</marquee>

<!-- Post Form -->
<form action="{% url 'posts:add_post' %}" role="form" method="post" enctype="multipart/form-data">
{% csrf_token %} 
<div class="card">
  <div class="card-content">
    <div class="columns is-mobile">
      <!-- Profile Pic -->  
      <div class="column is-narrow">
      <figure>
        <img src="{{request.user.profile.profile_pic.url}}" class="user-profile-pic">
      </figure>
    </div> 

    <!-- Thought -->
    <div class="column">
      {{form.body}}
      </div>
    </div>

    <!-- Attachments Modal -->
    <div id="modal_id_attachments" class="modal">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Attachments</p>
          <button class="delete" onclick="CloseModal('attachments')" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
          <span class="icon-text has-text-info" onclick="OpenModal('attachments')">
            <span class="icon">
              <i class="fa fa-link"></i>
            </span>
            <span>Link:&nbsp</span>
            <span>{{form.url}}</span>
          </span><br>

          <span class="icon-text has-text-success">
            <span class="icon">
              <i class="fa fa-image"></i>
            </span>
            <span>Pic:&nbsp</span>
            <span>{{form.pic}}</span>
          </span>

          <span class="icon-text has-text-danger">
            <span class="icon">
              <i class="fa fa-sticky-note"></i>
            </span>
            <span>PDF:&nbsp</span>
            <span>{{form.pdf}}</span>
          </span>

        </section>
        <footer class="modal-card-foot">
          <a onclick="CloseModal('attachments')" class="button is-rounded is-fullwidth is-link"><b>Save</b></a>
        </footer>
      </div>
    </div>
    <!-- End Attachments Modal -->

    <!-- Add Attachments -->
    <span class="icon-text has-text"  onclick="OpenModal('attachments')">
      <span class="icon">
        <i class="fa fa-paperclip fa-lg"></i>
      </span>
      <a><b>+Add Attachments</b></a>
    </span>
  
    <button class="button is-pulled-right is-rounded is-link"><b>Post</b></button>
    <br>
    <br>
  </div>
</div>
</form>
<br>

<!-- Feed -->
{% for post in posts %}
{% include 'posts/post-div.html' %}
{% empty %}
<center>
  Make more buddies, see posts from them in your feed
</center>
{% endfor %}

<script src="{% static 'js/FileSizeValidator.js' %}"></script>
{% endblock content %}

ncubook/templates/ncubook/login.html
{% extends 'ncubook/base.html' %}  
{% load static %}
{% block content %}

{% if form.errors %}
<!-- login error -->
<article class="message is-danger">
  <div class="message-body">
    Unable to Log In! Incorrect username or password.
  </div>
</article>
{% endif %}

        
<!-- Log in Form -->
<div class="columns is-centered has-text-centered">
  <div class="column is-half">
    <div id="id-login-card" class="card">
      <div class="card-content">
        <br>
        <img src="{% static 'images/logo-blue.png' %}" width="150" >
        <br><br>  
        <form role="form" method="post" autocomplete="off">
          {% csrf_token %}

          <!-- Username -->
          <div class="field">
            <div class="control has-icons-left has-icons-right">
              <input class="input is-rounded is-link" type="text" name="username"  placeholder="Username" maxlength="30" autofocus="" id="id_username"required>
              <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
            </div>
          </div>

          <!-- Password -->
          <div class="field">
            <div class="control has-icons-left has-icons-right">
              <input class="input is-rounded is-link" type="password" name="password" placeholder="Password" autocomplete="current-password" id="id_password" required>
              <span class="icon is-small is-left"><i class="fa fa-key"></i></span>
            </div>
          </div>

          <!-- Submit Button -->
          <div class="field">
            <div class="control">
              <button class="button is-fullwidth is-link is-rounded" name="action" type="submit">
                <b>Log In</b>
              </button>
            </div>
          </div>
          <br>

          {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}"/>
            {% else %}
            <input type="hidden" name="next" value="{% url 'ncubook:index' %}"/>
          {% endif %}

        </form>

        <!-- Password Reset Link -->
        <p class="subtitle is-6 ">
          Forgot password?
          <a href="{% url 'users:password_reset_confirm' %}">Password Reset</a>
        </p>

        <!-- Sign Up Link -->
        <p class="subtitle is-6 ">
          Don't have an account?
          <a href="{% url 'users:signup' %}">Sign Up</a>
        </p>
        <br>

      </div>
    </div>

  </div>
</div>

<!-- Footer -->
<footer >
  <div class="content has-text-centered">

    <!-- Footer menu -->
    <p>
      <a href="{% url 'ncubook:about' %}">About | </a>
      <a href="{% url 'ncubook:contact' %}">Contact | </a>
      <a href="{% url 'ncubook:privacy' %}">Privacy | </a>
      <a href="{% url 'ncubook:terms' %}">Terms</a>
    </p>

    <!-- a Shikeb Khan production -->
    <p>a Shikeb Khan production<br>
    <!-- Footer copyright -->
    NCUbook © {% now "Y" %} </p>

  </div>
</footer>

{% endblock content %}

ncubook/templates/ncubook/privacy.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page Header -->
<center>
  <p class="title is-4 is-size-5-mobile">Privacy Policy</p>
  <hr class="page-header-hr">
</center>

<!-- NCUbook's Privacy Policy -->
<br>
<center>
<h2 class="title is-size-2 is-size-4-mobile">
  Privacy Page
</h2>
</center>

{% endblock content%}

ncubook/templates/ncubook/search.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Search Bar -->
<form action="{% url 'ncubook:search' %}" method="POST">
{% csrf_token %}
<div class="field is-grouped">
  <p class="control is-expanded">
    <input class="input is-rounded" name="q" type="text" placeholder="Name / Username / Roll No" value="{{query}}">
  </p>
  <p class="control">
    <button class="button is-rounded is-link" type="submit">
      <b>Search</b>
    </button>
  </p>
</div>
</form>
<br>

<!-- Search By Coarse -->
<div class="tags are-medium">
  {% for coarse_branch in coarse_branches %}
  <a href="{% url 'ncubook:search_by_coarse_branch' coarse_branch.title %}"
     class="tag is-rounded is-medium is-warning"><b>{{coarse_branch.title}}</b>
  </a>
  {% endfor %}
</div>

<!-- Search Results -->
{% for user in users %}
{% include 'users/user-div.html' %}
{% endfor %}

{% endblock content %}

ncubook/templates/ncubook/terms.html
{% extends 'ncubook/base.html' %}
{% load static %}
{% block content %}

<!-- Page Header -->
<center>
  <p class="title is-4 is-size-5-mobile">Terms & Conditions</p>
  <hr class="page-header-hr">
</center>

<!-- NCUbook's Terms -->
<br>
<center>
<h2 class="title is-size-2 is-size-4-mobile">
  Terms Page
</h2>
</center>
{% endblock content %}